hoistPattern:
  - '*'
hoistedDependencies: {}
included:
  dependencies: true
  devDependencies: true
  optionalDependencies: true
injectedDeps: {}
layoutVersion: 5
nodeLinker: isolated
packageManager: pnpm@6.32.10
pendingBuilds: []
prunedAt: Wed, 28 Feb 2024 14:20:45 GMT
publicHoistPattern:
  - '*'
registries:
  default: https://registry.npmjs.org/
skipped:
  - /fsevents/2.3.3
storeDir: /home/workspace/.pnpm-store/v3
virtualStoreDir: .pnpm
